<?php
/**
 * @file
 * Module file for static map.
 */

/**
 * Implements hook_block_info().
 */
function embarq_map_block_info() {
  $blocks['embarq_map'] = array(
    'info' => t('Embarq Map'),
    // 'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function embarq_map_block_view($delta = '') {
  switch ($delta) {
    case 'embarq_map':
      $block['content'] = map_contents();
      break;
  }

  return $block;
}

/**
 * A module-defined block content function.
 */
function map_contents() {
  global $base_url;
  global $base_path;

  $output = '<div class="block">';
    $output .= '<div class="block-content map-list item-list">';
      $output .= '<ul class="list--ruled">';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://wricidades.org/"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Brasil-color_Low_R01_0.png" alt="Ross Center Brasil"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://wri.org.cn"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-China-color_Low_R01.png" alt="Ross Center China"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://wricitiesindia.org"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-India-color_Low_R01_0.png" alt="Ross Center India"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://wriciudades.org/"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Mexico-color_Low_R01_0.png" alt="Ross Center Mexico Mexico"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://wrisehirler.org"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Turkey-color_Low_R03_0.png" alt="Ross Center Turkey"></a>';
        $output .= '</li>';

      $output .= '</ul>';
    $output .= '</div>';
  $output .= '</div>';

  $output .= '<div class="static-map-container">';
    $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-bkg.png" alt="World Map" class="static-map">';

    $output .= '<a href="http://wrirosscities.org" class="map-pin map-pin--usa">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin.png" alt="Ross Center United States">';
    $output .= '</a>';

    $output .= '<a href="http://wri.org.cn" class="map-pin map-pin--china">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-china.png" alt="Ross Center China">';
    $output .= '</a>';

    $output .= '<a href="http://wriciudades.org/" class="map-pin map-pin--mexico">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-mexico.png" alt="Ross Center Mexico">';
    $output .= '</a>';

    $output .= '<a href="http://wricidades.org/" class="map-pin map-pin--brasil">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-brasil.png" alt="Ross Center Brasil">';
    $output .= '</a>';

    $output .= '<a href="http://wricitiesindia.org" class="map-pin map-pin--india">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-india.png" alt="Ross Center India">';
    $output .= '</a>';

    $output .= '<a href="http://wrisehirler.org" class="map-pin map-pin--turkiye">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-turkiye.png" alt="Ross Center Turkey">';
    $output .= '</a>';

  $output .= '</div> <!-- end of .static-map-container -->';

  return $output;
}
