<?php
/**
 * @file
 * Module file for static map.
 */

/**
 * Implements hook_block_info().
 */
function embarq_map_block_info() {
  $blocks['embarq_map'] = array(
    'info' => t('Embarq Map'),
    // 'cache' => DRUPAL_CACHE_PER_ROLE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function embarq_map_block_view($delta = '') {
  switch ($delta) {
    case 'embarq_map':
      $block['content'] = map_contents();
      break;
  }

  return $block;
}

/**
 * A module-defined block content function.
 */
function map_contents() {
  global $base_url;
  global $base_path;

  $output = '<div class="block">';
    $output .= '<div class="block-content map-list item-list">';
      $output .= '<ul class="list--ruled">';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://embarqbrasil.org/"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Brasil-color_Low_R01_0.png" alt=""></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://www.wrirosscities.org/geography/china"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-China-color_Low_R01.png" alt="EMBARQ China"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://embarqindia.org/"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-India-color_Low_R01_0.png" alt=""></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://embarqmexico.org/"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Mexico-color_Low_R01_0.png" alt="EMBARQ Mexico"></a>';
        $output .= '</li>';

        $output .= '<li class="list-item">';
          $output .= '<a href="http://embarqturkiye.org/en"><img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/logos/WRI-logo-Turkey-color_Low_R03_0.png" alt="EMBARQ Turkiye"></a>';
        $output .= '</li>';

      $output .= '</ul>';
    $output .= '</div>';
  $output .= '</div>';

  $output .= '<div class="static-map-container">';
    $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-bkg.png" alt="World Map" class="static-map">';

    $output .= '<a href="http://embarq.org/" class="map-pin map-pin--usa">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin.png" alt="EMBARQ USA">';
    $output .= '</a>';

    $output .= '<a href="http://wri.org.cn" class="map-pin map-pin--china">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-china.png" alt="EMBARQ China">';
    $output .= '</a>';

    $output .= '<a href="http://embarqmexico.org/" class="map-pin map-pin--mexico">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-mexico.png" alt="EMBARQ Mexico">';
    $output .= '</a>';

    $output .= '<a href="http://embarqbrasil.org/" class="map-pin map-pin--brasil">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-brasil.png" alt="EMBARQ Brasil">';
    $output .= '</a>';

    $output .= '<a href="http://embarqindia.org/" class="map-pin map-pin--india">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-india.png" alt="EMBARQ India">';
    $output .= '</a>';

    $output .= '<a href="http://embarqturkiye.org/en" class="map-pin map-pin--turkiye">';
      $output .= '<img src="' . $base_path . drupal_get_path('theme', 'wri') . '/images/map/map-pin-turkiye.png" alt="EMBARQ Turkiye">';
    $output .= '</a>';

  $output .= '</div> <!-- end of .static-map-container -->';

  return $output;
}
